### ISSUE TITLE
Missing code mappings for SOFA score

### ISSUE THREAD

**Issue by ppazos** [ehrbase/fhir-bridge#250]
There are missing codes for the mapping of the SOFA score.

## Steps to reproduce ## 

POST the sofa score JSON.

## Actual result ##

Failure during REST processing: ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: Either the code cvs0 or ns4 is not valid for the cardiovaskular score

## Expected result ##

Should map without problems.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by ppazos** [comment]
The problem is the SOFA.opt is missing those codes.

1. The OPT should have those codes https://simplifier.net/forschungsnetzcovid-19/sofa-score-cs
2. The Java code in SofaScoreCode should be updated
3. The Java code in SofaScoreObservationConverter should be updated
4. Rerun the robot tests to verify the issue is solved

**Comment by ppazos** [comment]
BLOCKED BY: the OPT should be updated.

**Comment by ppazos** [comment]
The OPT was updated: https://ckm.highmed.org/ckm/templates/1246.169.1056

**Comment by SevKohler** [comment]
fixed by newest commit, can you check that @ppazos

**Comment by ppazos** [comment]
@SevKohler after pulling for branch fix_sofa_score, recompiling, retesting and comparing the results, the json generated is the same (has the same issue as the one I checked before, the code for ordinal 3 is still at0008 instead of the correct at0018), are the changes on that branch? Maybe I'm pulling from the wrong branch.

```
{
    "_type": "COMPOSITION",
    "archetype_details": {
        "archetype_id": {
            "value": "openEHR-EHR-COMPOSITION.registereintrag.v1"
        },
        "rm_version": "1.0.4",
        "template_id": {
            "value": "SOFA"
        }
    },
    "archetype_node_id": "openEHR-EHR-COMPOSITION.registereintrag.v1",
    "category": {
        "_type": "DV_CODED_TEXT",
        "defining_code": {
            "_type": "CODE_PHRASE",
            "code_string": "433",
            "terminology_id": {
                "_type": "TERMINOLOGY_ID",
                "value": "openehr"
            }
        },
        "value": "event"
    },
    "composer": {
        "_type": "PARTY_SELF"
    },
    "content": [
        {
            "_type": "OBSERVATION",
            "archetype_node_id": "openEHR-EHR-OBSERVATION.sofa_score.v0",
            "data": {
                "archetype_node_id": "at0001",
                "events": [
                    {
                        "_type": "POINT_EVENT",
                        "archetype_node_id": "at0002",
                        "data": {
                            "_type": "ITEM_TREE",
                            "archetype_node_id": "at0003",
                            "items": [
                                {
                                    "_type": "ELEMENT",
                                    "archetype_node_id": "at0004",
                                    "name": {
                                        "_type": "DV_TEXT",
                                        "value": "Respiration"
                                    },
                                    "value": {
                                        "_type": "DV_ORDINAL",
                                        "symbol": {
                                            "_type": "DV_CODED_TEXT",
                                            "defining_code": {
                                                "_type": "CODE_PHRASE",
                                                "code_string": "at0008",
                                                "terminology_id": {
                                                    "_type": "TERMINOLOGY_ID",
                                                    "value": "local"
                                                }
                                            },
                                            "value": "Mechanisch bel..ftet und PaO.../FiO... 100-199 mmHg"
                                        },
                                        "value": 3
                                    }
                                },
                                {
                                    "_type": "ELEMENT",
                                    "archetype_node_id": "at0010",
                                    "name": {
                                        "_type": "DV_TEXT",
                                        "value": "Kardiovaskul..res System"
                                    },
                                    "value": {
                                        "_type": "DV_ORDINAL",
                                        "symbol": {
                                            "_type": "DV_CODED_TEXT",
                                            "defining_code": {
                                                "_type": "CODE_PHRASE",
                                                "code_string": "at0012",
                                                "terminology_id": {
                                                    "_type": "TERMINOLOGY_ID",
                                                    "value": "local"
                                                }
                                            },
                                            "value": "MAD < 70 mmHg"
                                        },
                                        "value": 1
                                    }
                                },
                                {
                                    "_type": "ELEMENT",
                                    "archetype_node_id": "at0016",
                                    "name": {
                                        "_type": "DV_TEXT",
                                        "value": "Zentrales Nervensystem"
                                    },
                                    "value": {
                                        "_type": "DV_ORDINAL",
                                        "symbol": {
                                            "_type": "DV_CODED_TEXT",
                                            "defining_code": {
                                                "_type": "CODE_PHRASE",
                                                "code_string": "at0021",
                                                "terminology_id": {
                                                    "_type": "TERMINOLOGY_ID",
                                                    "value": "local"
                                                }
                                            },
                                            "value": "GCS < 6"
                                        },
                                        "value": 4
                                    }
                                },
                                {
                                    "_type": "ELEMENT",
                                    "archetype_node_id": "at0022",
                                    "name": {
                                        "_type": "DV_TEXT",
                                        "value": "Nierenfunktion"
                                    },
                                    "value": {
                                        "_type": "DV_ORDINAL",
                                        "symbol": {
                                            "_type": "DV_CODED_TEXT",
                                            "defining_code": {
                                                "_type": "CODE_PHRASE",
                                                "code_string": "at0027",
                                                "terminology_id": {
                                                    "_type": "TERMINOLOGY_ID",
                                                    "value": "local"
                                                }
                                            },
                                            "value": "Kreatinin ... 5,0 mg/dL oder UOP < 200 mL/24h"
                                        },
                                        "value": 4
                                    }
                                },
                                {
                                    "_type": "ELEMENT",
                                    "archetype_node_id": "at0028",
                                    "name": {
                                        "_type": "DV_TEXT",
                                        "value": "Leberfunktion"
                                    },
                                    "value": {
                                        "_type": "DV_ORDINAL",
                                        "symbol": {
                                            "_type": "DV_CODED_TEXT",
                                            "defining_code": {
                                                "_type": "CODE_PHRASE",
                                                "code_string": "at0030",
                                                "terminology_id": {
                                                    "_type": "TERMINOLOGY_ID",
                                                    "value": "local"
                                                }
                                            },
                                            "value": "Bilirubin 1,2-1,9 mg/dL"
                                        },
                                        "value": 1
                                    }
                                },
                                {
                                    "_type": "ELEMENT",
                                    "archetype_node_id": "at0034",
                                    "name": {
                                        "_type": "DV_TEXT",
                                        "value": "Blutgerinnung"
                                    },
                                    "value": {
                                        "_type": "DV_ORDINAL",
                                        "symbol": {
                                            "_type": "DV_CODED_TEXT",
                                            "defining_code": {
                                                "_type": "CODE_PHRASE",
                                                "code_string": "at0037",
                                                "terminology_id": {
                                                    "_type": "TERMINOLOGY_ID",
                                                    "value": "local"
                                                }
                                            },
                                            "value": "Thrombozyten < 100 (x10../..L)"
                                        },
                                        "value": 2
                                    }
                                },
                                {
                                    "_type": "ELEMENT",
                                    "archetype_node_id": "at0041",
                                    "name": {
                                        "_type": "DV_TEXT",
                                        "value": "Gesamtergebnis"
                                    },
                                    "value": {
                                        "_type": "DV_COUNT",
                                        "magnitude": 6
                                    }
                                }
                            ],
                            "name": {
                                "_type": "DV_TEXT",
                                "value": "Tree"
                            }
                        },
                        "name": {
                            "_type": "DV_TEXT",
                            "value": "Beliebiges Ereignis zu einem Zeitpunkt"
                        },
                        "time": {
                            "_type": "DV_DATE_TIME",
                            "value": "2020-09-16T00:00:00-03:00"
                        }
                    }
                ],
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Event Series"
                },
                "origin": {
                    "_type": "DV_DATE_TIME",
                    "value": "2020-09-16T00:00:00-03:00"
                }
            },
            "encoding": {
                "_type": "CODE_PHRASE",
                "code_string": "UTF-8",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "IANA_character-sets"
                }
            },
            "language": {
                "_type": "CODE_PHRASE",
                "code_string": "de",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_639-1"
                }
            },
            "name": {
                "_type": "DV_TEXT",
                "value": "SOFA score"
            },
            "subject": {
                "_type": "PARTY_SELF"
            }
        }
    ],
    "context": {
        "_type": "EVENT_CONTEXT",
        "setting": {
            "_type": "DV_CODED_TEXT",
            "defining_code": {
                "_type": "CODE_PHRASE",
                "code_string": "232",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "openehr"
                }
            },
            "value": "secondary medical care"
        },
        "start_time": {
            "_type": "DV_DATE_TIME",
            "value": "2020-09-16T00:00:00-03:00"
        }
    },
    "feeder_audit": {
        "_type": "FEEDER_AUDIT",
        "originating_system_audit": {
            "_type": "FEEDER_AUDIT_DETAILS",
            "system_id": "FHIR-Bridge"
        },
        "originating_system_item_ids": [
            {
                "_type": "DV_IDENTIFIER",
                "id": "Observation/1/_history/1",
                "type": "fhir_logical_id"
            }
        ]
    },
    "language": {
        "_type": "CODE_PHRASE",
        "code_string": "de",
        "terminology_id": {
            "_type": "TERMINOLOGY_ID",
            "value": "ISO_639-1"
        }
    },
    "name": {
        "_type": "DV_TEXT",
        "value": "SOFA-Score"
    },
    "territory": {
        "_type": "CODE_PHRASE",
        "code_string": "DE",
        "terminology_id": {
            "_type": "TERMINOLOGY_ID",
            "value": "ISO_3166-1"
        }
    }
}
```

**Comment by ppazos** [comment]
@SevKohler tested develop branch and still see the same data going to the EHRBASE: at0008 should be at0018 (which is mapped to ordinal 3 for element at0004):

```
{
            "_type" : "ELEMENT",
            "name" : {
              "_type" : "DV_TEXT",
              "value" : "Respiration"
            },
            "value" : {
              "_type" : "DV_ORDINAL",
              "symbol" : {
                "_type" : "DV_CODED_TEXT",
                "value" : "Mechanisch bel..ftet und PaO.../FiO... 100-199 mmHg",
                "defining_code" : {
                  "_type" : "CODE_PHRASE",
                  "terminology_id" : {
                    "_type" : "TERMINOLOGY_ID",
                    "value" : "local"
                  },
                  "code_string" : "at0008"
                }
              },
              "value" : 3
            },
            "archetype_node_id" : "at0004"
          }

```

**Comment by SevKohler** [comment]
@ppazos 
Thats not the case for the updated SOFA score as far as i can see it:
https://ckm.highmed.org/ckm/templates/1246.169.1056
You are referring to the old sofa score coding where at0018 was the number, now its at0008 at least thats whats in the opt, as far as i can see it ?
Did you stop and delete ehrbase containers if using docker, the database has to be rebuilded in order to test, i just tested it with @BirgitSaalfeld where it worked.
We did the following things:
1. stop containers
2. delete ehrbase and postgres container
3. rebuild & restart ehrbase and postgres
4. rerun fhir bridge
5. send ehr create & sofa score

**Comment by ppazos** [comment]
@SevKohler just checked the last version of the OPT in the bridge and has the mapping correct to at0008:

 ```
<list>
                              <value>3</value>
                              <symbol>
                                <value/>
                                <defining_code>
                                  <terminology_id>
                                    <value>local</value>
                                  </terminology_id>
                                  <code_string>at0008</code_string>
                                </defining_code>
                              </symbol>
                            </list>
```

The problem is the bridge is not updating the template in ehrbase.

IMO, it should force the update of the template to ehrbase if the template was updated in the bridge. Without this, it will be an issue to update systems in production.

I'm not using containers, this is a local deployment of all the systems.

**Comment by SevKohler** [comment]
Yeah we already talked about that internally. Its already noted, can we close this issue then ?

**Comment by ppazos** [comment]
@SevKohler +1
